FROM node:6
ARG SENSI_DATALOGGING
ARG SENSI_MONITOR_MONGO_CONNECTION_STRING
ARG SENSI_MONITOR_MONGO_COLLECTION
ARG SENSI_EMAIL_ALERTS
ARG SENSI_MONITOR_EMAIL_TO
ARG SENSI_MONITOR_EMAIL_FROM
ARG SENSI_ALERT_RUNNING_MODE
ARG SENSI_ALERT_SYSTEM_MODE
ARG SENSI_ALERT_SETPOINT
ARG SENSI_ALERT_OMIT_SCHEDULED
ARG SENSI_USERNAME
ARG SENSI_PASSWORD
ARG SENSI_VERBOSE

COPY . /opt/sensi-monitor
WORKDIR /opt/sensi-monitor
RUN npm install 
CMD ["node", "sensi-monitor.js"]


